name: Deploy to Firebase Hosting after Merge

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v6

      - name: Set up Flutter
        id: flutter-action
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: .fvmrc
          cache: true
          pub-cache: true

      - name: Conditionally run melos bootstrap
        if: steps.flutter-action.outputs.PUB-CACHE-HIT != 'true'
        run: melos bootstrap

      - name: Verify Flutter installation
        run: flutter --version
      - name: Install dependencies
        run: flutter pub get
      - name: Build WASM
        run: flutter build web --wasm
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_PORTFOLIO_REDIAHMDS }}
          channelId: live
          projectId: portfolio-rediahmds

      